import type { Skill } from "./types"

export const skills: Skill[] = [
  {
    id: "html",
    name: "HTML",
    icon: "/images/icons/html.png",
    level: "core",
    projectIds: [
      "coffee-app",
      "portfolio-app",
      "portfolio-v1",
      "top-movies",
      "restaurant",
      "headphone-shop",
      "segal-rayane",
    ],
  },
  {
    id: "css",
    name: "CSS",
    icon: "/images/icons/css.png",
    level: "core",
    projectIds: [
      "coffee-app",
      "portfolio-app",
      "portfolio-v1",
      "top-movies",
      "restaurant",
      "headphone-shop",
      "segal-rayane",
    ],
  },
  {
    id: "javascript",
    name: "JavaScript",
    icon: "/images/icons/javascript.png",
    level: "core",
    projectIds: [
      "coffee-app",
      "portfolio-app",
      "portfolio-v1",
      "top-movies",
      "restaurant",
      "headphone-shop",
      "segal-rayane",
    ],
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: "/images/icons/typescript.png",
    level: "core",
    projectIds: [],
  },
  {
    id: "react",
    name: "React",
    icon: "/images/icons/reactjs.png",
    level: "core",
    projectIds: [],
  },
  {
    id: "redux",
    name: "Redux",
    icon: "/images/icons/redux.png",
    level: "familiar",
    projectIds: [],
  },
  {
    id: "vue",
    name: "Vue.js",
    icon: "/images/icons/vuejs.png",
    level: "familiar",
    projectIds: [],
  },
  {
    id: "nodejs",
    name: "Node.js",
    icon: "/images/icons/nodejs.png",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    icon: "/images/icons/bootstrap.png",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    icon: "/images/icons/tailwind.png",
    level: "core",
    projectIds: [],
  },
  {
    id: "python",
    name: "Python",
    icon: "/images/icons/python.png",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "git",
    name: "Git",
    icon: "/images/icons/git.png",
    level: "core",
    projectIds: [
      "coffee-app",
      "portfolio-app",
      "portfolio-v1",
      "top-movies",
      "restaurant",
      "headphone-shop",
      "segal-rayane",
    ],
  },
]

export const skillLevelLabel = {
  core: { fa: "اصلی", en: "Core" },
  proficient: { fa: "مسلط", en: "Proficient" },
  familiar: { fa: "آشنا", en: "Familiar" },
} as const
