import type { Skill } from "./types"

/** Full skill set from resume — keep complete, do not trim for display. */
export const skills: Skill[] = [
  {
    id: "html",
    name: "HTML5",
    icon: "/images/icons/html.png",
    category: "frontend",
    level: "core",
    projectIds: ["iziran", "segal"],
  },
  {
    id: "css",
    name: "CSS3",
    icon: "/images/icons/css.png",
    category: "frontend",
    level: "core",
    projectIds: ["iziran", "segal"],
  },
  {
    id: "javascript",
    name: "JavaScript (ES6+)",
    icon: "/images/icons/javascript.png",
    category: "frontend",
    level: "core",
    projectIds: ["iziran", "ariko", "segal"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: "/images/icons/typescript.png",
    category: "frontend",
    level: "core",
    projectIds: ["iziran", "ariko"],
  },
  {
    id: "rest",
    name: "RESTful API",
    category: "backend",
    level: "core",
    projectIds: ["iziran", "ariko", "arnitex"],
  },
  {
    id: "grpc",
    name: "gRPC",
    category: "backend",
    level: "proficient",
    projectIds: ["arnitex"],
  },
  {
    id: "react",
    name: "React.js",
    icon: "/images/icons/reactjs.png",
    category: "frontend",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    category: "frontend",
    level: "core",
    projectIds: [],
  },
  {
    id: "redux",
    name: "Redux Toolkit",
    icon: "/images/icons/redux.png",
    category: "frontend",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "tanstack-query",
    name: "TanStack Query",
    category: "frontend",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    icon: "/images/icons/tailwind.png",
    category: "frontend",
    level: "core",
    projectIds: [],
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    icon: "/images/icons/bootstrap.png",
    category: "frontend",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "antd",
    name: "Ant Design",
    category: "frontend",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "mui",
    name: "Material UI",
    category: "frontend",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "fuse",
    name: "Fuse Skeleton",
    category: "frontend",
    level: "proficient",
    projectIds: ["iziran"],
  },
  {
    id: "angular",
    name: "Angular",
    category: "frontend",
    level: "proficient",
    projectIds: ["ariko"],
  },
  {
    id: "nestjs",
    name: "NestJS",
    category: "backend",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "nodejs",
    name: "Node.js",
    icon: "/images/icons/nodejs.png",
    category: "backend",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "data",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "keycloak",
    name: "Keycloak & JWT",
    category: "backend",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "docker",
    name: "Docker",
    category: "devops",
    level: "core",
    projectIds: ["iziran"],
  },
  {
    id: "kafka",
    name: "Kafka",
    category: "devops",
    level: "proficient",
    projectIds: ["iziran"],
  },
  {
    id: "java",
    name: "Java",
    category: "backend",
    level: "core",
    projectIds: ["iziran", "ariko", "segal"],
  },
  {
    id: "spring-boot",
    name: "Spring Boot",
    category: "backend",
    level: "core",
    projectIds: ["iziran", "ariko"],
  },
  {
    id: "jpa",
    name: "JPA",
    category: "data",
    level: "proficient",
    projectIds: ["iziran", "ariko"],
  },
  {
    id: "maven",
    name: "Maven",
    category: "backend",
    level: "proficient",
    projectIds: ["ariko"],
  },
  {
    id: "gradle",
    name: "Gradle",
    category: "backend",
    level: "proficient",
    projectIds: ["ariko"],
  },
  {
    id: "redis",
    name: "Redis",
    category: "data",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    category: "devops",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "sqlserver",
    name: "SQL Server",
    category: "data",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "git",
    name: "Git",
    icon: "/images/icons/git.png",
    category: "other",
    level: "core",
    projectIds: ["iziran", "ariko", "segal"],
  },
  {
    id: "linux",
    name: "Linux OS",
    category: "devops",
    level: "proficient",
    projectIds: [],
  },
  {
    id: "python",
    name: "Python",
    icon: "/images/icons/python.png",
    category: "other",
    level: "familiar",
    projectIds: [],
  },
  {
    id: "rust",
    name: "Rust",
    category: "other",
    level: "familiar",
    projectIds: [],
  },
]

export const skillLevelLabel = {
  core: { fa: "اصلی", en: "Core" },
  proficient: { fa: "مسلط", en: "Proficient" },
  familiar: { fa: "آشنا", en: "Familiar" },
} as const

export function getAllSkills() {
  return skills
}
